version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.18
    network_mode: bridge
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"